petpals/forum/routes.py
from flask import Blueprint, render_template, request
from petpals.models import Post, Reply
from sqlalchemy import func, or_

from .utils import utility_processor

router = Blueprint(
    'forum_router', __name__, template_folder='templates', url_prefix='/forum'
)


@router.get('')
def forum():
    sort_by = request.args.get('sort_by', 'newest')
    page = request.args.get('page', 1, type=int)
    search = request.args.get('q')

    post_query = Post.query

    if search:
        post_query = post_query.filter(
            or_(Post.content.ilike(f'%{search}%'), Post.title.ilike(f'%{search}%'))
        )

    # desc: descending
    match sort_by:
        case 'newest':
            post_query = post_query.order_by(Post.timestamp.desc())
        case 'no_replies':
            post_query = post_query.outerjoin(Reply).filter_by(post_id=None)
        case 'most_replies':
            post_query = (
                post_query.outerjoin(Reply)
                .group_by(Post.post_id)
                .order_by(func.count(Reply.post_id).desc())
            )
        case 'most_viewed':
            post_query = post_query.order_by(Post.views.desc())

    posts = post_query.paginate(page=page, per_page=5)

    return render_template('forum.html', posts=posts, sort_by=sort_by, search=search)


router.context_processor(utility_processor)

petpals/home/routes.py
from flask import Blueprint, render_template

router = Blueprint('home_router', __name__, template_folder='templates')


@router.get('/')
def index():
    return render_template('index.html')


@router.get("/about")
def about():
    return render_template('about.html')


@router.get("/faq")
def faq():
    return render_template('faq.html')

petpals/messaging/routes.py
from flask import Blueprint, render_template, request, abort
from flask_login import current_user, login_required
from sqlalchemy import func, and_, or_, desc
from petpals import db, socket
from petpals.models import Messages, User

router = Blueprint(
    'message_router',
    __name__,
    url_prefix='/messages',
    template_folder='templates',
    static_folder="static",
)


@router.get('')
@login_required
def render_message_page():

    # This source was very useful: https://stackoverflow.com/a/45779686

    subqry = (
        db.session.query(
            Messages.conversation_id, func.max(Messages.time_sent).label("last_time")
        )
        .outerjoin(
            User,
            or_(
                User.username == Messages.sender_username,
                User.username == Messages.recipient_username,
            ),
        )
        .filter(User.id == current_user.id)
        .group_by(Messages.conversation_id)
        .subquery()
    )

    msg_query = Messages.query.join(
        subqry,
        and_(
            Messages.conversation_id == subqry.c.conversation_id,
            Messages.time_sent == subqry.c.last_time,
        ),
    ).order_by(desc(Messages.time_sent))

    def get_prof_pic(username):
        prof_pic_query = User.query.filter_by(username=username).first()
        return prof_pic_query.image_path

    return render_template(
        'messages.html', recent_messages=msg_query, get_prof_pic=get_prof_pic
    )


@router.get('/new')
@login_required
def render_new_conversation_page():
    usernames = []

    users = User.query.all()
    messages = Messages.query.all()

    for user in users:
        if current_user.username != user.username:
            usernames.append(user.username)

    for message in messages:
        if current_user.username == message.sender_username:
            if message.recipient_username in usernames:
                usernames.remove(message.recipient_username)
        elif current_user.username == message.recipient_username:
            if message.sender_username in usernames:
                usernames.remove(message.sender_username)

    return render_template(
        'new_message.html',
        usernames=sorted(usernames),
    )


@router.post('/new')
@login_required
def create_new_conversation():
    data = request.json
    new_message = Messages()

    next_conversation_id = 0
    conversation_id_query = db.session.query(
        func.max(Messages.conversation_id).label("highest_convo")
    )

    try:
        next_conversation_id = int(conversation_id_query.first()['highest_convo']) + 1
    except Exception:
        next_conversation_id = 1

    new_message.recipient_username = data['recipient']
    new_message.sender_username = data['sender']
    new_message.message = data['message']
    new_message.conversation_id = next_conversation_id

    db.session.add(new_message)
    db.session.commit()
    return {'convo_id': next_conversation_id}


@router.get("/conversation/<conversation_id>")
@login_required
def get_conversation(conversation_id):
    messages = Messages.query.filter_by(conversation_id=conversation_id).all()
    if len(messages) == 0:
        abort(404)
    elif (messages[0].sender_username == current_user.username) or (
        messages[0].recipient_username == current_user.username
    ):
        if messages[0].sender_username == current_user.username:
            recipient = messages[0].recipient_username
        else:
            recipient = messages[0].sender_username
    else:
        abort(403)

    return render_template(
        'conversation.html',
        recipient=recipient,
        messages=messages,
        conversation_id=conversation_id,
    )


@socket.on('message')
def handle_message(message):
    new_message = Messages()
    new_message.conversation_id = message['conversation_id']
    new_message.recipient_username = message['recipient']
    new_message.sender_username = message['sender']
    new_message.message = message['message']

    db.session.add(new_message)
    db.session.commit()

    socket.send(message)

petpals/profile/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from petpals import bcrypt, db
from petpals.models import Pet, User

from .forms import ChangePassword, UpdateAccountForm, UpdatePetForm
from .utils import save_profile_picture, save_recent_photo

router = Blueprint('profile_router', __name__, template_folder='templates')


@router.get('/user')
@login_required
def profile_current_user():
    return redirect(
        url_for('profile_router.profile_user', username=current_user.username)
    )


@router.get('/user/<username>')
def profile_user(username: str):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template('user_profile.html', user=user)


@router.route('/user/edit', methods=['GET', 'POST'])
@login_required
def profile_user_edit():
    form = UpdateAccountForm()
    # updates user data
    if form.validate_on_submit():
        # calls method save_picture to save picture and give filename
        if form.picture.data:
            picture_file = save_profile_picture(form.picture.data)
            # image_file is name in models.py
            current_user.image_file = picture_file

        current_user.fullname = form.fullname.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.biography = form.biography.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('profile_router.profile_current_user'))
    # auto populates fields with users current information
    elif request.method == 'GET':
        form.fullname.data = current_user.fullname
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.biography.data = current_user.biography

    return render_template(
        'edit_profile.html',
        title='Edit Profile',
        image_file=current_user.image_path,
        form=form,
    )


@router.route('/user/edit/password', methods=['GET', 'POST'])
@login_required
def profile_user_edit_password():
    form = ChangePassword()

    # validate current password
    # bcrypt the new password
    # set the new password to current_user.fullname = form.fullname.data

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # checks if user exists and password verifies with db
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            hashed_password = bcrypt.generate_password_hash(
                form.new_password.data
            ).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash(f'Your password has been updated!', 'success')
            return redirect(url_for('profile_router.profile_current_user'))
        else:
            flash('Login failed, please check email and password', 'danger')
    return render_template('edit_password.html', title='Edit Password', form=form)


@router.route('/user/edit/delete', methods=['POST'])
@login_required
def delete_profile():
    user = User.query.filter_by(username=current_user.username).first_or_404()
    if not current_user:
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('You account has been deleted!', 'success')
    return redirect(url_for('home_router.index'))


@router.route('/user/<username>/<pet_name>')
def profile_pet(username: str, pet_name: str):
    # pet = db.session.query(User, Pet).filter(
    #         User.username == username,
    #         Pet.name == pet_name
    #     ).first()

    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # Replace with pet's profile picture and recent images from DB
    return render_template('pet_profile.html', pet=pet)


@router.route('/pet/new', methods=['GET', 'POST'])
@login_required
def profile_pet_new():
    form = UpdatePetForm()
    if form.validate_on_submit():
        pet = Pet(
            name=form.name.data,
            species=form.species.data,
            subspecies=form.subspecies.data,
            color=form.color.data,
            tagline=form.tagline.data,
            biography=form.biography.data,
            user_id=current_user.id,
        )
        if form.profile_picture.data:
            picture_file = save_profile_picture(form.profile_picture.data, pet)
            pet.image_file = picture_file
        for i, str_i in enumerate(('one', 'two', 'three'), 1):
            field = getattr(form, f'picture_{str_i}')
            if field.data:
                recent_picture_file = save_recent_photo(field.data, pet, i)
                setattr(pet, f'img{i}_path', recent_picture_file)
        db.session.add(pet)
        db.session.commit()
        flash('You have added your pet!', 'success')
        return redirect(url_for('profile_router.profile_current_user'))
    return render_template('form_pet_profile.html', form=form, legend="New Pet")


@router.route('/user/<username>/<pet_name>/edit', methods=['GET', 'POST'])
@login_required
def profile_pet_edit(username: str, pet_name: str):
    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # only the pet owner can update the pet info
    if pet.owner != current_user:
        abort(403)
    form = UpdatePetForm()
    if form.validate_on_submit():
        # calls method save_picture to save picture and give filename
        if form.profile_picture.data:
            picture_file = save_profile_picture(form.profile_picture.data, pet)
            pet.image_file = picture_file
        for i, str_i in enumerate(('one', 'two', 'three'), 1):
            field = getattr(form, f'picture_{str_i}')
            if field.data:
                recent_picture_file = save_recent_photo(field.data, pet, i)
                setattr(pet, f'img{i}_path', recent_picture_file)

        pet.name = form.name.data
        pet.species = form.species.data
        pet.subspecies = form.subspecies.data
        pet.color = form.color.data
        pet.tagline = form.tagline.data
        pet.biography = form.biography.data
        db.session.commit()
        flash('You have updated your pets information!', 'success')
        return redirect(
            url_for(
                'profile_router.profile_pet',
                username=pet.owner.username,
                pet_name=pet.name,
            )
        )
    # auto populates the fields
    elif request.method == 'GET':
        form.name.data = pet.name
        form.species.data = pet.species
        form.subspecies.data = pet.subspecies
        form.color.data = pet.color
        form.tagline.data = pet.tagline
        form.biography.data = pet.biography
    return render_template(
        'form_pet_profile.html', pet=pet, form=form, legend="Update Pet"
    )


@router.route('/user/<username>/<pet_name>/delete', methods=['POST'])
@login_required
def delete_pet(username: str, pet_name: str):
    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # only the pet owner can update the pet info
    if pet.owner != current_user:
        abort(403)
    db.session.delete(pet)
    db.session.commit()
    flash('You pets profile has been deleted!', 'success')
    return redirect(url_for('profile_router.profile_current_user'))

petpals/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.ico">

    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MBD CSS -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.css"
      rel="stylesheet"
    />

    <!--Custom CSS-->
    <link rel="stylesheet" href="/static/style.css">

    <!-- MDB JS -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.js"
      defer
    ></script>

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav
      class="navbar navbar-expand-lg navbar-light bg-info"
    >
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand" href="{{ url_for('home_router.index') }}">
          <img
            src="/static/images/logo/logo.png"
            class="rounded"
            height="50"
            alt="Pet Pals"
            loading="lazy"
          />
        </a>
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fa-solid fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left links -->
          <div class="navbar-nav me-auto mb-2 mb-lg-0">
            <a
              class="nav-link{{' active' if active_page == 'index'}} text-white mt-2"
              href="{{ url_for('home_router.index') }}"
            >
              Home
            </a>
            <a
              class="nav-link{{' active' if active_page == 'forum'}} text-white mt-2"
              href="{{ url_for('forum_router.forum') }}"
            >
              Forum
            </a>
            <a
              class="nav-link{{' active' if active_page == 'about'}} text-white mt-2"
              href="{{ url_for('home_router.about') }}"
            >
              About Us
            </a>
          </div>
          <!-- Right elements -->
          <div class="d-flex align-items-center">
            {% if current_user.is_authenticated %}
            <a
              class="nav-link{{' active' if active_page == 'messages'}} text-white mt-2"
              href="{{ url_for('message_router.render_message_page') }}"
            >
              <i class="fa-solid fa-comment-dots fa-2xl"></i>
            </a>
              <!-- Avatar -->
              <div class="dropdown">
                <a
                  class="dropdown-toggle d-flex align-items-center text-body me-3"
                  href="{{ url_for('profile_router.profile_user', username=current_user.username) }}"
                  id="navbarDropdownMenuAvatar"
                  role="button"
                  data-mdb-toggle="dropdown"
                  data-mdb-display="static"
                  data-mdb-dropdown-animation="off"
                  aria-expanded="false"
                >
                  <img
                    src="{{ current_user.image_path }}"
                    class="rounded-circle"
                    height="50"
                    alt="@{{ current_user.username }}"
                    loading="lazy"
                  />
                </a>
                <ul
                  class="dropdown-menu dropdown-menu-start dropdown-menu-lg-end"
                  aria-labelledby="navbarDropdownMenuAvatar"
                >
                  <li>
                    <a
                    class="dropdown-item"
                    href="{{ url_for('profile_router.profile_user', username=current_user.username) }}"
                    >
                    My Profile
                    </a>
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{{ url_for('profile_router.profile_user_edit') }}"
                    >
                      Edit Profile
                    </a>
                  </li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="{{ url_for('auth_router.logout') }}"
                    >
                      Log Out
                    </a>
                  </li>
                </ul>
              </div>
            {% else %}
              <a
                class="btn btn-outline-dark btn-rounded me-3"
                href="{{ url_for('auth_router.login') }}"
              >
                Log In
              </a>
              <a
                class="btn btn-dark btn-rounded me-3"
                href="{{ url_for('auth_router.signup') }}"
              >
                Sign Up
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <!--Displays a flash message-->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <!--End flash message-->

    <div class="background-paws" style="min-height: calc(100vh - 134px);">
      {% block body %}{% endblock %}
    </div>
    

    <footer class="bg-info text-lg-start">
      <div class="text-center p-3">&copy; 2022 Pet Pals</div>
    </footer>
  </body>
</html>

petpals/templates/edit_post.html
{% extends '_layout.html' %}
{% block title %}New Post{% endblock %}
{% set active_page = 'post_form' %}

{% block body %}


<section class="bg-image background-paws">
    <div class="container py-5">
        <div class="card rounded-3 border border-info border-6">
            <div class="card-body p-md-5 mx-md-4">
                <div class="text-center">
                    <img src="/static/images/logo.jpeg" alt="Pet Pals" class="mb-1" />
                    <h5 class="mb-4">Where your Pet meets new Pals</h5>
                </div>
                <h1 class="text-center mb-5">Create New Post Form</h1>

                {% if current_user.is_authenticated %}

                <form method="POST">
                    {{ form.hidden_tag() }}
                    <!-- Title input -->
                    <div class="form-outline mb-4">
                        {{ form.title(class="form-control") }}
                        {{ form.title.label(class="form-label") }}
                    </div>

                    <!-- Content input -->
                    <div class="form-outline mb-3">
                        {{ form.content(class="form-control", rows="10") }}
                        {{ form.content.label(class="form-label") }}
                    </div>

                    <!--Disabling Attachment Function until implemented-->
                    <!--This may need to be deleted-->

                    <!-- Attachment input
          <div class="form-group mb-4">
            <label for="post-attachment" class="form-label">Attachment</label>
            <input
              name="post-attachment"
              id="post-attachment"
              type="file"
              class="form-control"
            />
          </div> -->

                    <!-- Submit button -->
                    <div class="text-center">
                        {{ form.submit(class="btn btn-info btn-block mb-3") }}
                    </div>
                </form>
                {% endif %}

            </div>
        </div>
    </div>
</section>

<script>
    document.querySelectorAll(".form-outline").forEach((formOutline) => {
        new mdb.Input(formOutline).init();
    });
</script>

{% endblock %}