petpals/profile/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from petpals import bcrypt, db
from petpals.models import Pet, User

from .forms import ChangePassword, UpdateAccountForm, UpdatePetForm
from .utils import save_profile_picture, save_recent_photo

router = Blueprint('profile_router', __name__, template_folder='templates')


@router.get('/user')
@login_required
def profile_current_user():
    return redirect(
        url_for('profile_router.profile_user', username=current_user.username)
    )


@router.get('/user/<username>')
def profile_user(username: str):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template('user_profile.html', user=user)


@router.route('/user/edit', methods=['GET', 'POST'])
@login_required
def profile_user_edit():
    form = UpdateAccountForm()
    # updates user data
    if form.validate_on_submit():
        # calls method save_picture to save picture and give filename
        if form.picture.data:
            picture_file = save_profile_picture(form.picture.data)
            # image_file is name in models.py
            current_user.image_file = picture_file

        current_user.fullname = form.fullname.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.biography = form.biography.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('profile_router.profile_current_user'))
    # auto populates fields with users current information
    elif request.method == 'GET':
        form.fullname.data = current_user.fullname
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.biography.data = current_user.biography

    return render_template(
        'edit_profile.html',
        title='Edit Profile',
        image_file=current_user.image_path,
        form=form,
    )


@router.route('/user/edit/password', methods=['GET', 'POST'])
@login_required
def profile_user_edit_password():
    form = ChangePassword()

    # validate current password
    # bcrypt the new password
    # set the new password to current_user.fullname = form.fullname.data

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # checks if user exists and password verifies with db
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            hashed_password = bcrypt.generate_password_hash(
                form.new_password.data
            ).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash(f'Your password has been updated!', 'success')
            return redirect(url_for('profile_router.profile_current_user'))
        else:
            flash('Login failed, please check email and password', 'danger')
    return render_template('edit_password.html', title='Edit Password', form=form)


@router.route('/user/edit/delete', methods=['POST'])
@login_required
def delete_profile():
    user = User.query.filter_by(username=current_user.username).first_or_404()
    if not current_user:
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('You account has been deleted!', 'success')
    return redirect(url_for('home_router.index'))


@router.route('/user/<username>/<pet_name>')
def profile_pet(username: str, pet_name: str):
    # pet = db.session.query(User, Pet).filter(
    #         User.username == username,
    #         Pet.name == pet_name
    #     ).first()

    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # Replace with pet's profile picture and recent images from DB
    return render_template('pet_profile.html', pet=pet)


@router.route('/pet/new', methods=['GET', 'POST'])
@login_required
def profile_pet_new():
    form = UpdatePetForm()
    if form.validate_on_submit():
        pet = Pet(
            name=form.name.data,
            species=form.species.data,
            subspecies=form.subspecies.data,
            color=form.color.data,
            tagline=form.tagline.data,
            biography=form.biography.data,
            user_id=current_user.id,
        )
        if form.profile_picture.data:
            picture_file = save_profile_picture(form.profile_picture.data, pet)
            pet.image_file = picture_file
        for i, str_i in enumerate(('one', 'two', 'three'), 1):
            field = getattr(form, f'picture_{str_i}')
            if field.data:
                recent_picture_file = save_recent_photo(field.data, pet, i)
                setattr(pet, f'img{i}_path', recent_picture_file)
        db.session.add(pet)
        db.session.commit()
        flash('You have added your pet!', 'success')
        return redirect(url_for('profile_router.profile_current_user'))
    return render_template('form_pet_profile.html', form=form, legend="New Pet")


@router.route('/user/<username>/<pet_name>/edit', methods=['GET', 'POST'])
@login_required
def profile_pet_edit(username: str, pet_name: str):
    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # only the pet owner can update the pet info
    if pet.owner != current_user:
        abort(403)
    form = UpdatePetForm()
    if form.validate_on_submit():
        # calls method save_picture to save picture and give filename
        if form.profile_picture.data:
            picture_file = save_profile_picture(form.profile_picture.data, pet)
            pet.image_file = picture_file
        for i, str_i in enumerate(('one', 'two', 'three'), 1):
            field = getattr(form, f'picture_{str_i}')
            if field.data:
                recent_picture_file = save_recent_photo(field.data, pet, i)
                setattr(pet, f'img{i}_path', recent_picture_file)

        pet.name = form.name.data
        pet.species = form.species.data
        pet.subspecies = form.subspecies.data
        pet.color = form.color.data
        pet.tagline = form.tagline.data
        pet.biography = form.biography.data
        db.session.commit()
        flash('You have updated your pets information!', 'success')
        return redirect(
            url_for(
                'profile_router.profile_pet',
                username=pet.owner.username,
                pet_name=pet.name,
            )
        )
    # auto populates the fields
    elif request.method == 'GET':
        form.name.data = pet.name
        form.species.data = pet.species
        form.subspecies.data = pet.subspecies
        form.color.data = pet.color
        form.tagline.data = pet.tagline
        form.biography.data = pet.biography
    return render_template(
        'form_pet_profile.html', pet=pet, form=form, legend="Update Pet"
    )


@router.route('/user/<username>/<pet_name>/delete', methods=['POST'])
@login_required
def delete_pet(username: str, pet_name: str):
    user = User.query.filter_by(username=username).first_or_404()
    pet = user.pets.filter_by(name=pet_name).first_or_404()
    # only the pet owner can update the pet info
    if pet.owner != current_user:
        abort(403)
    db.session.delete(pet)
    db.session.commit()
    flash('You pets profile has been deleted!', 'success')
    return redirect(url_for('profile_router.profile_current_user'))

petpals/profile/templates/edit_profile.html
{% extends '_layout.html' %}
{% block title %}Edit Profile{% endblock %}
{% set active_page = 'edit_profile' %}

{% block body %}

<section>
  <div class="container py-5 h-100">
    <div class="card rounded-3 text-black border border-info border-6">
      <div class="card-body p-md-5 mx-md-4">
        <div class="text-center">
          <img src="{{ image_file }}" alt="logo" />
          <h4 class="card-title mb-0">{{current_user.fullname}}</h4>
          <h4 class="card-title mb-0">{{current_user.username}}</h4>
          <h4 class="card-title mb-0">{{current_user.email}}</h4>
        </div>
        <form method="POST" action="" enctype="multipart/form-data" novalidate>
          {{ form.hidden_tag() }}
          <h2 class="text-center m-5">Account Info</h2>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.fullname.errors %}
              {{ form.fullname(class="form-control" + (" is-invalid" if form.fullname.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.fullname.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.fullname(class="form-control") }}
            {% endif %}
            {{ form.fullname.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.username.errors %}
              {{ form.username(class="form-control" + (" is-invalid" if form.username.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control") }}
              {% endif %}
              {{ form.username.label(class="form-label") }}
          </div>
          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.email.errors %}
            {{ form.email(class="form-control" + (" is-invalid" if form.email.errors else "")) }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span class="">{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
              {{ form.email(class="form-control") }}
              {% endif %}
              {{ form.email.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.biography.errors %}
              {{ form.biography(class="form-control", rows="5" + (" is-invalid" if form.biography.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.biography.errors %}
                  <span class="">{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.biography(class="form-control", rows="5") }}
            {% endif %}
            {{ form.biography.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            {{ form.picture.label() }} <br />
            {{ form.picture(class="form-control-file",  accept=".jpeg, .jpg, .png, .gif") }}
            <!--If error occurs, print errors-->
            {% if form.picture.errors %}
              {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span><br />
              {% endfor %}
            {% endif %}
          </div>

          <!--TODO Attatchment button-->
          <!-- <div class="form-group">
            <label for="exampleFormControlFile1">Attachments</label>
            <input type="file" class="form-control-file" />
          </div> -->

          <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{{ url_for('profile_router.profile_user_edit_password') }}">Change Password</a>
            </small>
          </div>

          <div class="text-center pt-1 mb-0 pb-0">
            {{ form.submit(class="btn btn-info btn-block mb-3") }}
          </div>
        </form>

        <div class="text-center pt-1 mb-0 pb-0">
          <button type="button" class="btn btn-danger btn-sm m-1" data-mdb-toggle="modal" data-mdb-target="#deleteModal">Delete Account</button>

          <!-- Modal -->
          <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel"> Delete Account?</h5>
                  <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">This is not reversible!!! Are you sure?</div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                  <form action="{{  url_for('profile_router.delete_profile') }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                  </form>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

<script>
  document.querySelectorAll(".form-outline").forEach((formOutline) => {
    new mdb.Input(formOutline).init();
  });
</script>

{% endblock %}}

petpals/profile/templates/form_pet_profile.html
{% extends '_layout.html' %}
{% block title %}{{legend}}{% endblock %}
{% set active_page = 'form_pet_profile' %}

{% block body %}

<section>
  <div class="container py-5 h-100">
    <div class="card rounded-3 text-black border border-info border-6">
      <div class="card-body p-md-5 mx-md-4">
        <div class="text-center">
          <!--If pet exists then the page shows edit/delete info, otherwise it shows default which is for adding pet-->
          {% if pet %}
            <img src="{{ pet.image_path }}" alt="NONE" />
            <h4 class="card-title mb-0">{{pet.name}}</h4>
          {% endif %}
        </div>
        <form method="POST" action="" enctype="multipart/form-data" novalidate>
          {{ form.hidden_tag() }}
          <h2 class="text-center m-5">Pet Info</h2>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.name.errors %}
              {{ form.name(class="form-control" + (" is-invalid" if form.name.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.name.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.name(class="form-control") }}
            {% endif %}
            {{ form.name.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.species.errors %}
              {{ form.species(class="form-control" + (" is-invalid" if form.species.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.species.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.species(class="form-control") }}
              {% endif %}
              {{ form.species.label(class="form-label") }}
          </div>
          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.subspecies.errors %}
            {{ form.subspecies(class="form-control" + (" is-invalid" if form.subspecies.errors else "")) }}
            <div class="invalid-feedback">
              {% for error in form.subspecies.errors %}
              <span class="">{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
              {{ form.subspecies(class="form-control") }}
              {% endif %}
              {{ form.subspecies.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.color.errors %}
            {{ form.color(class="form-control" + (" is-invalid" if form.color.errors else "")) }}
            <div class="invalid-feedback">
              {% for error in form.color.errors %}
              <span class="">{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
              {{ form.color(class="form-control") }}
              {% endif %}
              {{ form.color.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.tagline.errors %}
            {{ form.tagline(class="form-control" + (" is-invalid" if form.tagline.errors else "")) }}
            <div class="invalid-feedback">
              {% for error in form.tagline.errors %}
              <span class="">{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
              {{ form.tagline(class="form-control") }}
              {% endif %}
              {{ form.tagline.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            <!--If error occurs, print errors-->
            {% if form.biography.errors %}
              {{ form.biography(class="form-control", rows="5" + (" is-invalid" if form.biography.errors else "")) }}
              <div class="invalid-feedback">
                {% for error in form.biography.errors %}
                  <span class="">{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.biography(class="form-control", rows="5") }}
            {% endif %}
            {{ form.biography.label(class="form-label") }}
          </div>

          <div class="form-outline mb-5">
            {{ form.profile_picture.label() }} <br />
            {{ form.profile_picture(class="form-control-file",  accept=".jpeg, .jpg, .png, .gif") }}
            <!--If error occurs, print errors-->
            {% if form.profile_picture.errors %}
              {% for error in form.profile_picture.errors %}
                <span class="text-danger">{{ error }}</span><br />
              {% endfor %}
            {% endif %}
          </div>

          <div class="form-outline mb-5">
            {{ form.picture_one.label() }} <br />
            {{ form.picture_one(class="form-control-file",  accept=".jpeg, .jpg, .png, .gif") }}
            <!--If error occurs, print errors-->
            {% if form.picture_one.errors %}
              {% for error in form.picture_one.errors %}
                <span class="text-danger">{{ error }}</span><br />
              {% endfor %}
            {% endif %}
          </div>

          <div class="form-outline mb-5">
            {{ form.picture_two.label() }} <br />
            {{ form.picture_two(class="form-control-file",  accept=".jpeg, .jpg, .png, .gif") }}
            <!--If error occurs, print errors-->
            {% if form.picture_two.errors %}
              {% for error in form.picture_two.errors %}
                <span class="text-danger">{{ error }}</span><br />
              {% endfor %}
            {% endif %}
          </div>

          <div class="form-outline mb-5">
            {{ form.picture_three.label() }} <br />
            {{ form.picture_three(class="form-control-file",  accept=".jpeg, .jpg, .png, .gif") }}
            <!--If error occurs, print errors-->
            {% if form.picture_three.errors %}
              {% for error in form.picture_three.errors %}
                <span class="text-danger">{{ error }}</span><br />
              {% endfor %}
            {% endif %}
          </div>
          <div class="text-center pt-1 mb-0 pb-0">
            {{ form.submit(class="btn btn-info btn-block mb-3") }}
          </div>
        </form>
        <!--If pet exists then the page shows edit/delete info, otherwise it shows default which is for adding pet-->
        {% if pet %}
          <div class="text-center pt-1 mb-0 pb-0">
            <button type="button" class="btn btn-danger btn-sm m-1" data-mdb-toggle="modal" data-mdb-target="#deleteModal">Delete Pet</button>

            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel"> Delete Pet?</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">This is not reversible!!! Are you sure?</div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                    <form action="{{  url_for('profile_router.delete_pet', username=pet.owner.username, pet_name=pet.name) }}" method="POST">
                      <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

<script>
  document.querySelectorAll(".form-outline").forEach((formOutline) => {
    new mdb.Input(formOutline).init();
  });
</script>

{% endblock %}}

petpals/profile/templates/pet_profile.html
{% extends '_layout.html' %}
{% block title %}{{ pet.name }}'s Profile{% endblock %}
{% set active_page = 'pet_profile' %}

{% block body %}

<!-- HACK: Used min-height style to stretch paws background -->
<section>
  <div class="container py-3 h-100">
    <div class="row py-1 px-2">
      <div class="col-md-8 mx-auto">
        <!-- Profile widget -->
        <div class="bg-white shadow rounded overflow-hidden border border-6 border-info">
          <!-- Profile Head -->
          <div class="px-4 pt-4 pb-2 cover">
            <div class="profile-head d-flex align-items-end">
              <div class="me-3">
                <img src="{{pet.image_path}}" width="130" class="rounded img-thumbnail" />
              </div>
              <div class="text-white me-3 mb-2">
                <h4 class="mb-0">{{ pet.name }}</h4>
                <p class="mb-0">
                  <a href="{{ url_for('profile_router.profile_user', username=pet.owner.username) }}"
                    class="text-muted hover-blue text-decoration-underline">{{ pet.owner.fullname }}'s Pet</a>
                </p>
                {% if current_user.is_authenticated and current_user == pet.owner %}
                <div class="mb-4">
                  <a href="{{ url_for('profile_router.profile_pet_edit', username=pet.owner.username, pet_name=pet.name) }}"
                    class="btn btn-light hover-gray btn-outline-dark btn-sm">Edit profile</a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          <!-- Profile Statistics -->
          <div class="bg-dark profile-gray p-4 d-flex justify-content-end text-center">
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block">3</h5>
                <small class="text-muted">
                  <i class="fas fa-image me-2"></i>Photos</small>
              </li>
              <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block">0</h5>
                <small class="text-muted">
                  <i class="fas fa-user me-2"></i>Followers</small>
              </li>
              <li class="list-inline-item">
                <h5 class="font-weight-bold mb-0 d-block">0</h5>
                <small class="text-muted">
                  <i class="fas fa-user me-2"></i>Following</small>
              </li>
            </ul>
          </div>
          <div class="px-4 py-3">
            <h5 class="mb-0">About</h5>
            <div class="p-4 rounded shadow-sm bg-dark profile-gray">
              {% if pet.biography %}
              {% for line in pet.biography.splitlines() %}
              <p class="mb-0">{{ line }}</p>
              {% endfor %}
              {% endif %}
            </div>
          </div>
          <div class="py-4 px-4">
            <div class="d-flex align-items-center justify-content-between mb-3">
              <h5 class="mb-0">Recent photos</h5>
              <a href="#" class="btn btn-link text-muted">Show all</a>
            </div>
            <div class="row">
              {% for image in pet.recent_photo_paths %}
              <div class="col-md-4 mb-2 pr-lg-1">
                <img src="{{image}}" onclick="window.open(this.src, '_blank');" class="img-fluid rounded hover-shadow"
                  style="cursor:pointer" />
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

petpals/profile/templates/user_profile.html
{% extends '_layout.html' %}
{% block title %}{{ user.fullname }}'s Profile{% endblock %}
{% set active_page = 'user_profile' %}

{% block body %}

<section>
  <div>
    <div class="row profile-margins mx-auto py-5">
      <div class="col-sm-1 mx-auto bg-info rounded-2 profile-margins">
        <div class="card flex-row my-3 mx-2 border-0 shadow rounded-3 overflow-hidden">
          <div class="profile-left d-md-flex bg-gray">
            <div class="row text-center my-auto">
              <div class="mb-1 bg-w p-3">
                <img class="border border-0 p-4" src="{{ user.image_path }}" width="300"
                  class="rounded img-thumbnail" />
                <h1 class="mt-2 text-white">{{ user.fullname }}</h1>
                {% if current_user.is_authenticated and current_user.username == user.username %}
                <div>
                  <a class="btn btn-warning btn-rounded btn-sm mb-3 text-white"
                    href="{{ url_for('profile_router.profile_user_edit') }}"
                    class="btn btn-light hover-gray btn-outline-dark btn-sm">Edit profile</a>
                  <a class="btn btn-warning btn-rounded btn-sm mb-3 text-white"
                    href="{{ url_for('profile_router.profile_pet_new') }}">Add More Pets</a>
                </div>
                {% endif %}
              </div>
              <div class="text-white my-5">
                {% if user.biography %}
                {% for line in user.biography.splitlines() %}
                <p class="mb-0">{{ line }}</p>
                {% endfor %}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="card-body p-2 p-sm-4">
            <div class="text-center mb-3 mt-2">
              <h1>My Pets</h1>
            </div>
            <hr class="my-3">
            <div id="carouselExampleControls" class="carousel slide" data-mdb-ride="carousel">
              <div class="carousel-inner">
                {% for pet in user.pets %}
                <div class="carousel-item {% if loop.index == 1 %} active{% endif %}">
                  <a href="{{ url_for('profile_router.profile_pet', username=pet.owner.username, pet_name=pet.name) }}">
                    <div class="card">
                      <img src="{{ pet.image_path }}" class="card-img-top" />
                      <div class="card-body">
                        <h5 class="card-title text-center">{{ pet.name }}</h5>
                      </div>
                    </div>
                  </a>
                </div>
                {% endfor %}
              </div>
              <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleControls"
                data-mdb-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleControls"
                data-mdb-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}